### ISSUE TITLE
I got memory error

### ISSUE THREAD

**Issue by liqi6811** [lukewhyte/textpack#1]
Hi Luke, 

I tried your code, got below memory error. 

Thank you. 

---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-3-9819547f0d3e> in <module>
     10   tfidf_matrix.transpose(),
     11   vals.size,
---> 12   0.8
     13 )

c:\Anaconda\lib\site-packages\sparse_dot_topn\awesome_cossim_topn.py in awesome_cossim_topn(A, B, ntop, lower_bound, use_threads, n_jobs)
     41 
     42     indptr = np.empty(M+1, dtype=idx_dtype)
---> 43     indices = np.empty(nnz_max, dtype=idx_dtype)
     44     data = np.empty(nnz_max, dtype=A.dtype)
     45 

MemoryError:

**Comment by lukewhyte** [comment]
Hi @liqi6811, apologies, I hadn't been checking the issues on this repo!

It's possible you're getting a memory error due to your systems overcommit handling mode. Check out this StackOverflow post: https://stackoverflow.com/questions/57507832/unable-to-allocate-array-with-shape-and-data-type

**Comment by lukewhyte** [comment]
Closing and adding this warning to README
